apps/urls.py
from django.contrib import admin
from django.urls import path,re_path
from apps import views

app_name = '[apps]'  #include需要添加app_name
urlpatterns = [
    re_path('^$',views.index,name='index')

]

djangoweb/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from apps import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('first',views.first),
    path('jquery-1.12.4.js',views.jquery),
    re_path('^(<id>\d+)$',views.hero),#<关键字名>关键字参数用法，没有则使用位置参数匹配
    path('apps/',include('apps.urls',namespace='apps')),#namespace在include中，name在path中，用于反向解析
    path('verifyCode/',views.verifyCode)

]

apps/models.py
from django.db import models

# Create your model

class BookInfoMange(models.Manager):
    def get_queryset(self):
        return super(BookInfoMange,self).get_queryset().filter()  #重写get_queryset方法
    def create(cls,title,autor,pub_date):  #第二种方法,在管理器中使用对象方法，推荐使用这种方法
        b = BookInfo()
        b.btitle =title
        b.autor = autor
        b.bpub_date = pub_date   #b = BookInfo.books2.create(参数) b.save()
        return b

class BookInfo(models.Model):
    #init方法会报错，因为继承的类Model里已经在用init,重写会直接覆盖Model中的init，导致里面的init不能用
    # ，可以调用类方法@classmethod
    btitle = models.CharField(max_length=20)
    autor = models.CharField(max_length=20,verbose_name='作者') #verbose_name 为admin页面显示名字
    bpub_date = models.DateTimeField(db_column='发布时间')#db_column为数据库列名
    books = models.Manager()#自定义模型类 和默认object一样 BookInfo.books.all() ==BookInfo.object.all()查询
    books2 = BookInfoMange()
    def __str__(self):
        return self.btitle
    class Meta:
        db_table ='bookinfo'#修改数据库表的名称，默认为应用名_模型名 apps_bookinfo
    @classmethod
    def create(cls,title,autor,pub_date):  #调用类方法的参数，不能用self，self调用init方法里的参数
        b = BookInfo()
        b.btitle =title
        b.autor = autor
        b.bpub_date = pub_date   #b = BookInfo.create(参数) b.save()
        return b

class HeroInfo(models.Model):
    hname = models.CharField(max_length=20)
    hgender = models.BooleanField()
    hcontent = models.CharField(max_length=1000)
    hbook = models.ForeignKey(BookInfo,on_delete=models.CASCADE,db_column='book1')

apps/views.py
from django.shortcuts import render
from django.http import HttpResponse
from apps.models import *
from PIL import ImageDraw,ImageFont,Image
import random

from django.db.models import Max


# Create your views here.

def index(request):
    return HttpResponse('hello world')


def first(request):
    booklist = BookInfo.books.all()
    context = {'list':booklist}
    return render(request,'无缝滚动.html',context)

def jquery(request):
    return render(request,'jquery-1.12.4.js')

def hero(request,id):
    # list = BookInfo.books.filter(heroinfo__hcontent__contains='六')筛选英雄名包含六的书名
    # list = BookInfo.books2.filter(pk__lte=3)筛选id小于等于3的
    # Max1 = BookInfo.books.aggregate(Max(pk)) id最大的
    # list = BookInfo.books.filter(pk__lt=F('bcommet'))id小于评论数的
    # list = BookInfo.books.filter(pk__lt =3,btitle__contains='1')and用法
    # list = BookInfo.books.filter(Q(pk__lt =3)|Q(btitle__contains='1'))or用法
    #a = request.GET['a'] 获取get参数，?a=1&b=2一键一值
    # a = request.GET['a'] ?a=1&a=2&a=3获取最后一个a值
    # a = request.GET.getlist('a') ?a=1&a=2&a=3获取所有a值
    book = BookInfo.books.get(pk=id)
    heroli = book.heroinfo_set.all()
    context = {'hero':heroli}
    return render(request,'hero.html',context)
#cookie练习
def cookieTest(request):
    response = HttpResponse() #构造response对象
    cookie = request.COOKIES
    if cookie.has_key('t1'):
        response.write(cookie['t1'])#往response中写入request的cookie
    #response.set_cookie('t1'为key,'abc'为value,过期时间)
    return response

#session练习
def session(request):
    uname = request.session[key值]
    # request.session.set_expiry(10)  10秒后过期
    # request.session.set_expiry(timedelta(days=5))
    # request.session.set_expiry(0) 浏览器关闭后过期
    # request.session.set_expiry(None)  永不过期
    context = {'uname':uname}
    return render(request,'',context)

#html转义练习
def htmlTest(request):
    context = {'t1':'<h1>123<h1>'}
    return render(request,'hero.html',context)

#验证码
def verifyCode(requset):
    #创建背景色

    bgcolor = (random.randrange(50,100),random.randrange(50,150),255)
    #设置宽高
    width = 100
    height = 35
    #创建画布
    image = Image.new('RGB',(width,height),bgcolor)
    #创建画笔
    draw = ImageDraw.Draw(image)
    #创建字体样式
    font = ImageFont.truetype(font=r'D:\Users\Administrator\PycharmProjects\djangoweb\venv\cambriab.ttf',size=25)
    #创建字体
    text = 'QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm0123456789'
    #random.choices是从text里随机选择4个值，取出的值为列表，再转化为str类型
    draw.text((20,0),''.join(random.choices(text,k=4)),(255,255,255),font=font)
    #保存到内存流
    from io import BytesIO
    buf = BytesIO() #图片用bytes，不能用stringio
    image.save(buf,'png')
    return HttpResponse(buf.getvalue(),'image/png')

templates/hero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <div>
        <ui>
{#            {{ t1|safe }}html转义#}
{#            {{ t1|default:'<h1>123<h1>' }}#}
{#            {% url 'apps:index' 参数 %}模板继承#}

            {% for h in hero %}
            <li>{{ h.hname }}</li>
            {% endfor %}
        </ui>
    </div>
</body>
</html>

templates/javascript.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>document</title>
    <link type="text/css" href="1.css" rel="stylesheet" id="css">
    <script>
        window.onload=function(){
        var oBox = document.getElementById('box1');
        var oDiv2 = document.getElementById('div2');
        var btn = document.getElementById('btn');
        var d =document.getElementById('div1');
        var oInput1 =document.getElementById('input1');
        var oInput2 =document.getElementById('input2');
        var oInput3 =document.getElementById('input3');
        btn.onclick=function () {
            if(oDiv2.style.display=='none'){
                oDiv2.style.display='block';
            }
            else{
                oDiv2.style.display='none';
            }


        }







        input3.onclick=function(){
            var oA =sum(oInput1.value,oInput2.value);
            alert('计算结果为：'+oA);
        }
        function sum(a,b){
            var c = parseInt(a)+parseInt(b);

            return c;
        }
        // input1.value='10';
        // input2.value= '5';
        d.onclick =function () {alert('hello')

        };
        oBox.onclick = cssb;
        // window.onload=function(){
        //
        // var a = document.getElementById('box1');
        //var b =document.getElementById('box2');
        //     a.onclick=cssa;
        // b.onclick=cssb};
        function cssa() {
            var c = document.getElementById('css');
            c.href='1.css';
        }
        function cssb() {
            var c = document.getElementById('css');
            c.href='2.css';

        }}
    </script>
    <style type="text/css">
        #div2{
            width: 88px;
            height: 150px;
            background-color: darkmagenta;
        }
    </style>
</head>
<body>
<div id="div1">这是一个div元素</div>

<input type="button" value="按钮1" id="box1">
<input type="button" value="按钮2" id="box2">

<input type="button" value="切换" id="btn">
    <div  id="div2" >
    </div>

    <div class="boxb"
        <input type="text" name="" value="" id="input1">
        <input type="text" name="" value="" id="input2">
        <input type="button" name="" value="相加" id="input3">
    </div>
</body>
</html>

templates/test.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <title>第一个网页</title>
    <!--外链式-->
    <script type="text/javascript" src="js地址"></script>
    <!--嵌入式-->
    <script type="text/javascript">
        window.onload = function(){document.getElementById('box').title='nihao'}
    </script>


    <style type="text/css">
        label{color: darkred;}
        #lab1{color: blue;}

        .box{width: 200px;
        height: 100px;
        background-color: darkred;
        border: 20px solid #5038ff;
        padding: 20px }

        .box:hover{background-color: aquamarine}

        /*border-top: 10px solid #5038ff;*/
        /*border-left: 10px solid #5038ff;*/
        /*border-right: 10px solid #5038ff;*/
        /*border-bottom: 10px solid #5038ff;*/

        /*border-top-width: 20px;*/
        /*border-top-color: ;*/
        /*border-top-style: solid;}*/
        .box1{width: 400px;
            height: 35px;
            background-color: antiquewhite;
            margin: auto;
            border-top:#f00 solid 1px ;
            border-bottom: 3px solid #666;
            font-size: 20px;
            font-family: "Microsoft Himalaya";
            color: #333;
        }
        .box1{padding-left:15px;
        padding-top:15px;

        }


    </style>

</head>
<body>
<!--第一种js嵌入方式行间事件，不推荐-->
<input type="button" name="" value="弹框" onclick="alert('hello')">
<ul>
    <!--#表示锚点 JavaScript：表示没有动作-->
    <li><a href="javascript:;">1 &</a></li>
    <li><a href="#">2</a></li>
    <li><a href="#">3</a></li>
</ul>

<h2>css盒子模型</h2>
<div id="box"  class="box" title="盒子">
盒子里面的文字fdasfdsf adfdfdsfsdf

</div>
<!--<script type="text/javascript">-->
        <!--// alert('hello,world');-->
        <!--document.getElementById('box').title='wokandao';-->
    <!--</script>-->

<h4>新闻列表</h4>
<div class="box1">
新闻列表

</div>

<table border="1" width="500"  height="300">
    <tr>
        <th>name</th>
        <th>date</th>
        <th>age</th>
    </tr>
    <tr>
        <td align="center">jack</td>
        <td>2017-6-1</td>
        <td>20</td>
    </tr>



</table>
<h3>用户注册</h3>
    <form action="http://www.baidu.com">
        <div>
            <label id="lab1" for="username">用户名：</label>
            <input type="text" name="" id="username">
        </div>
        <br>
        <div>
            <label>密 码 ：</label>
            <input type="password" name="">
        </div>
        <br>
        <div>
            <label>性别</label>
            <input type="radio" name="gender"id="male"><label for="male">男</label>
            <input type="radio" name="gender">女
        </div>
        <div>
            <label>照片</label>
            <input type="file" name="">
        </div>
        <br>
        <div>
            <label>爱好</label>
            <input type="checkbox" name="gender">游戏
            <input type="checkbox" name="gender">逛街
            <input type="checkbox" name="gender">电影
            <input type="checkbox" name="gender">音乐
        </div>
         <br>
        <div>
            <label>籍贯</label>
            <select>
                <option>浙江</option>
                <option>上海</option>
                <option>北京</option>
                <option>广东</option>
                <option>厦门</option>
            </select>
        </div>
        <br>
        <div>
            <input type="submit" name="" value="提交" >
            <input type="reset" name="" value="重置">
        </div>

    </form>
<a href="http://www.baidu.com" title="跳转到百度"> <img src="01.jpg" alt="柯南"></a>
</body>
</html>

templates/vip.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>vip视频解析</title>
    <script src="jquery-1.12.4.js"></script>
    <script>
        $(function () {
                var oUrl1 = $('#url1').val();
                var oUrl2 =$('.form-search');
                switch (oUrl1){
                    case '0':
                        oUrl2.attr('action',"https://660e.com/?url=");
                        break;
                    case '1':
                        oUrl2.action = "http://jx.hxbte.cn/jx.php/?url=";
                        break;

                }



        })
    </script>

</head>
<body>
    <div class="box1">
        <lable>接口</lable>
        <select name="" id="url1">
            <option value="0">接口1</option>
            <option value="1">接口2</option>
            <option value="2">接口3</option>
            <option value="3">接口4</option>
            <option value="4">接口5</option>
            <option value="5">接口6</option>
            <option value="6">接口7</option>
            <option value="7">接口8</option>


        </select>
        <form class="form-search cf" action="" method="get">
            <input name="url" id="url" type="text" class="text" placeholder="请输入播放地址">
            <input type="submit" id="post" class="button" value="立即播放">
        </form>
    </div>
</body>
</html>

templates/倒计时.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>倒计时</title>
    <script>
        window.onload = function () {


            timer();
            var sec = new timer2();
            setInterval(timer,1000);
            var oTime =setInterval(timer2,1000);






            function timer2() {
                var oDiv2 = document.getElementById('div2')
                var now =new Date()
                var futurenum ='7 20,2018 14:33:00'
                var future = new Date(futurenum);
                var lefts = parseInt((future-now)/1000);
                var oDay = parseInt((lefts/86400));
                var oHour = parseInt((lefts%86400)/3600);
                var oMin = parseInt(((lefts%86400)%3600)/60);
                var oSec = lefts%60;
                oDiv2.innerHTML =('距离'+futuretime(futurenum)+'还有'+oDay+'天'+oHour+'小时'+oMin+'分钟'+oSec+'秒');
                if(oSec<= 0){
                    window.location.href ='http://www.baidu.com'
                }

            }
            function futuretime(future) {
                var time = new Date(future);
                var year = time.getFullYear();
                var month = time.getMonth();
                var day = time.getDate();
                var hour = time.getHours();
                var minute = time.getMinutes();
                var second = time.getSeconds();
                return  year +'-' + (month+1) + '-' + day + ' '+ hour + ':' +seconds(minute) +':'+seconds(second)
            }
            function timer() {
                var oDiv1 = document.getElementById("div1");
                var time = new Date();
                var year = time.getFullYear();
                var month = time.getMonth();
                var day = time.getDate();
                var hour = time.getHours();
                var minute = time.getMinutes();
                var second = time.getSeconds();

                oDiv1.innerHTML ='现在时间为：'+ year +'-' + (month+1) + '-' + day + ' '+ hour + ':' +seconds(minute) +':'+seconds(second);

            }

            function seconds(num) {
                if(num<10){
                    var sencond = '0'+num;
                    return sencond;
            }
                else{
                    return num;
            }

        }
                }

    </script>
</head>
<body>
    <div id="div1"></div>
    <div id="div2"></div>
</body>
</html>

templates/动画.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>动画</title>
    <script type="text/javascript"src="jquery-1.12.4.js"></script>
    <script>
        $(function () {
            $('#div1').animate({width:400,height:400},1000,function () {
                 $(this).animate({marginRight:0},1000);




            });
            $('.list li').each(function(index){
                $(this).html(index);
            });


        })



    </script>
    <style type="text/css">
        #div1{
            width: 200px;
            height: 200px;
            background-color: darkred;
            margin-left:0;
        }
    </style>
</head>
<body>
    <div id="div1">盒子</div>
    <ul class="list">
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
        <li></li>
    </ul>

</body>
</html>

templates/定时器.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>定时器</title>
    <script>
        window.onload=function () {
            var oBox = document.getElementById('box');
            var oBox3 =document.getElementById('box3');
            var left =20
            var timer3 =setInterval(function () {
                left +=2;
                oBox3.style.left =left +'px';
                if(left>700){
                    clearTimeout(timer3);
                }

            },50);
            // 执行一次定时器
            var timer = setTimeout(function () {
                oBox.style.display = 'block';
            }, 4000);

            // 关闭定时器
            clearTimeout(timer);
            // 反复执行定时器
            var timer2 = setInterval(function () {
                ;

            }, 2000);

        }
    </script>
    <style type="text/css">
        .box{
            display: block;
        }
        .box1{
            width: 300px;
            height: 300px;
            background-color: white;
            border: 1px black solid;
            position: fixed;
            left: 50%;
            top: 50%;
            margin-left: -150px;
            margin-top: -150px;
            /*盖住box2*/
            z-index: 999;

        }
        .box2{
            position: fixed;
            width: 100%;
            height: 100%;
            background-color: black;
            left: 0;
            top: 0;
            /*淡化背景*/
            opacity: 0.3;
            filter: alpha(opacity=30);
            z-index: 9990;

        }
        #box3{
            width: 100px;
            height: 100px;
            background-color: blue;
            position: fixed;

            z-index: 9999;
        }
    </style>
</head>
<body>
    <h2>首页</h2>
    <div class="box" id="box">

    <div class="box1">
        <h1>提示</h1>
    </div>
        <div class="box2"></div>
        <div id="box3">11</div>
    </div>
</body>
</html>

templates/无缝滚动.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>无缝滚动</title>
    <script src="jquery-1.12.4.js"></script>
    <script>
        $(function () {
            var deraction = 2;
            var $ul = $('#slide ul');
            var left = 0;
            $ul.html($ul.html()+$ul.html());

            var timer = setInterval(move,50);


            function move() {
                if(left<-500){
                    left =0;
                }
                if(left > 0 ){
                    left = -500;
                }
                left -= deraction;
                $ul.css({left:left})

            };

            $('#btn1').click(function () {
                deraction =2;

            });
            $('#btn2').click(function () {
                deraction = -2;
            });

            $ul.mouseover(function () {
                clearInterval(timer);
            });

            $ul.mouseout(function () {
                timer = setInterval(move,50);

            });

        })

    </script>
    <style type="text/css">
        body,ul,li{margin: 0;padding: 0}
        ul{list-style: none;}
        .slide{
            width: 500px;
            height: 100px;
            border: 1px solid black;
            margin: 20px auto 0;
            position: relative;
            overflow: hidden;
        }

        .slide ul{
            position: absolute;
            width: 1000px;
            height: 100px;
            left: 0;
            top: 0;
        }

        .slide ul li{
            width: 90px;
            height: 90px;
            margin: 5px;
            background-color: #ccc;
            line-height: 90px;
            text-align: center;
            font-size: 30px;
            float: left;
        }
        .btns{
            width: 500px;
            height: 50px;
            margin: 10px auto 0;
        }

        .left{
            text-align: left;
        }
    </style>
</head>
<body>
    <div>
        <form action="csrf1" method="post"></form>
{#        csrf保护，防止其他网站数据post到csrf1中,只限post请求#}
        {% csrf_token %}
        <input type="text" name="uname">
        <input type="submit" value="提交">
    </div>
    <div>
        <ul>
            {% for book in list %}
            <li class="left"><a href="{{ book.id }}">{{ book.btitle  }}</a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="btns">
        <input type="button" name="" value="向左" id="btn1">
        <input type="button" name="" value="向右" id="btn2">

    </div>
    <div class="slide" id="slide">
        <ul>
            <li>1</li>
            <li>2</li>
            <li>3</li>
            <li>4</li>
            <li>5</li>
        </ul>
    </div>


</body>
</html>

templates/计算器.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>计算器</title>
    <script type="text/javascript">
        window.onload=function(){
            var oNum1=document.getElementById('num1');
            var oNum2=document.getElementById('num2')
            var oOpt = document.getElementById('opt');
            var oCal = document.getElementById('cal');
            oCal.onclick=function () {
                var Num1=oNum1.value;
                var Num2=oNum2.value;
                var Opt=oOpt.value;
                
                switch (Opt){
                    case '0':
                        var oSum=parseInt(Num1)+parseInt(Num2);
                        alert(oSum);
                        break;
                    case '1':
                        var odum=parseInt(Num1)-parseInt(Num2);
                        alert(odum);
                        break;
                    case '2':
                        var oaum=parseInt(Num1)*parseInt(Num2);
                        alert(oaum);
                        break;
                    case '3':
                        var oqum=parseInt(Num1)/parseInt(Num2);
                        alert(oqum);
                        break;


                }
                // if(Opt=='0'){
                //     var oSum=parseInt(Num1)+parseInt(Num2);
                //     alert(oSum);
                // };
                // if(Opt=='1'){
                //     var odum=parseInt(Num1)-parseInt(Num2);
                //     alert(odum);
                // };
                // if(Opt=='2'){
                //     var oaum=parseInt(Num1)*parseInt(Num2);
                //     alert(oaum);
                // };
                // if(Opt=='3'){
                //     var oqum=parseInt(Num1)/parseInt(Num2);
                //     alert(oqum);
                // };
            };


        }
    </script>
</head>
<body>
    <input id="num1" type="text" name="">
    <select id="opt">
        <option value="0">+</option>
        <option value="1">-</option>
        <option value="2">*</option>
        <option value="3">/</option>
    </select>
    <input id="num2" type="text" name="">
    <input id="cal" type="button" name="" value="计算">
</body>
</html>